"""Dashboard filters: turning the viewer's choices into SQL, safely.

A chart's SQL carries a `{{ filters }}` token where its WHERE clause will accept
more terms. At render time the token becomes the conjunction of the filters that
are active *and* in scope for that chart, as bound parameters.

Two decisions worth knowing:

* **The token, not a wrapper.** Wrapping a chart's query
  (`SELECT * FROM (chart) WHERE c_id = ...`) cannot filter on a column the chart
  grouped away, which is most of them. The filter has to land inside the
  original query, before aggregation — so the query has to say where.
* **Columns are configuration, values are input.** `column_expr` is written by
  whoever edits the dashboard and goes into the SQL text. The value comes from
  the URL and is always a bound parameter. Never mix the two up.
"""

import re
from dataclasses import dataclass, field
from datetime import date

TOKEN = "{{ filters }}"
# Tolerate the spacing people actually type.
TOKEN_RE = re.compile(r"\{\{\s*filters\s*\}\}")

SELECT, DATERANGE, TEXT = "select", "daterange", "text"
FILTER_TYPES = (
    (SELECT, "Pick from a list", "Values come from a query you supply"),
    (DATERANGE, "Date range", "A from/to pair on a date column"),
    (TEXT, "Free text", "Matches with ILIKE %value%"),
)
FILTER_TYPE_KEYS = {k for k, _, _ in FILTER_TYPES}

# A filter key becomes a bind-parameter name and a query-string key.
KEY_RE = re.compile(r"^[a-z][a-z0-9_]{0,39}$")


def valid_key(key: str) -> bool:
    return bool(KEY_RE.match(key or ""))


@dataclass
class ActiveFilter:
    """One filter with the value the viewer chose."""

    key: str
    label: str
    filter_type: str
    column_expr: str
    values: list[str] = field(default_factory=list)  # select: chosen; daterange: [from, to]
    applies_to: list[str] = field(default_factory=list)

    def scopes(self, chart_slug: str) -> bool:
        """Empty scope means every chart carrying the token."""
        return not self.applies_to or chart_slug in self.applies_to

    @property
    def is_set(self) -> bool:
        return any(v not in (None, "") for v in self.values)


def _parse_date(value: str) -> date | None:
    try:
        return date.fromisoformat(value.strip())
    except (ValueError, AttributeError):
        return None


def build_clause(active: list[ActiveFilter], chart_slug: str) -> tuple[str, dict]:
    """(SQL fragment, bound params) for one chart.

    The fragment always starts with AND, so it drops into an existing WHERE.
    Charts generated by the Superset import end with `WHERE ... {{ filters }}`
    or `WHERE 1=1 {{ filters }}` for exactly this reason.
    """
    terms: list[str] = []
    params: dict = {}

    for f in active:
        if not f.is_set or not f.scopes(chart_slug):
            continue
        if f.filter_type == SELECT:
            chosen = [v for v in f.values if v != ""]
            if not chosen:
                continue
            names = []
            for i, value in enumerate(chosen):
                name = f"flt_{f.key}_{i}"
                params[name] = value
                names.append(f":{name}")
            terms.append(f"{f.column_expr} IN ({', '.join(names)})")
        elif f.filter_type == DATERANGE:
            start = _parse_date(f.values[0]) if len(f.values) > 0 else None
            end = _parse_date(f.values[1]) if len(f.values) > 1 else None
            if start:
                params[f"flt_{f.key}_from"] = start
                terms.append(f"{f.column_expr} >= :flt_{f.key}_from")
            if end:
                params[f"flt_{f.key}_to"] = end
                terms.append(f"{f.column_expr} <= :flt_{f.key}_to")
        elif f.filter_type == TEXT:
            value = (f.values[0] if f.values else "").strip()
            if not value:
                continue
            params[f"flt_{f.key}"] = f"%{value}%"
            terms.append(f"{f.column_expr} ILIKE :flt_{f.key}")

    if not terms:
        return "", {}
    return " AND " + " AND ".join(terms), params


def apply(sql: str, active: list[ActiveFilter], chart_slug: str) -> tuple[str, dict]:
    """Substitute the token in `sql`. Returns the SQL and its bound params.

    A chart with no token comes back untouched and unfiltered — deliberately
    visible rather than silently half-filtered, so the dashboard can say which
    charts a filter doesn't reach.
    """
    if not TOKEN_RE.search(sql):
        return sql, {}
    clause, params = build_clause(active, chart_slug)
    return TOKEN_RE.sub(lambda _: clause, sql), params


def accepts_filters(sql: str) -> bool:
    """Whether this chart's SQL has somewhere to put a filter."""
    return bool(TOKEN_RE.search(sql))


def strip_token(sql: str) -> str:
    """The SQL as it runs with no filters — for previews and the SQL tab."""
    return TOKEN_RE.sub("", sql)


def resolve(definitions: list, values: dict[str, list[str]]) -> list[ActiveFilter]:
    """Pair stored filter definitions with what the viewer picked.

    `values` is the query string, already parsed to key -> list of strings. A
    filter with nothing chosen still comes back (the bar has to render it), it
    simply contributes no SQL.
    """
    active = []
    for d in definitions:
        chosen = values.get(d.key)
        if chosen is None:
            chosen = [d.default_value] if d.default_value else []
        active.append(
            ActiveFilter(
                key=d.key,
                label=d.label,
                filter_type=d.filter_type,
                column_expr=d.column_expr,
                values=list(chosen),
                applies_to=list(d.applies_to or []),
            )
        )
    return active
